import time

from selenium import webdriver
from selenium.webdriver import ActionChains

driver=webdriver.Chrome()
driver.get("http://localhost:8080/sis/public/page/main.html")
driver.maximize_window()
time.sleep(3)
driver.find_element_by_xpath("//*[@id='login_form']/div[2]/div/input").send_keys("abc")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='login_form']/div[3]/div/input").send_keys("123")
time.sleep(3)
driver.find_element_by_xpath("//*[@id='login_form']/div[6]/input[2]").click()
time.sleep(10)
div=driver.find_element_by_class_name("modal-footer")
div.find_element_by_xpath("//*[@id='main_fail_modal_dialog']/div/div[3]/button").click()
time.sleep(5)
driver.find_element_by_id("stu_tab").click()
time.sleep(10)
driver.find_element_by_id("stu_table_toolbar_add").click()
time.sleep(6)
driver.find_element_by_id("stu_table_toolbar_add_form_studentName").send_keys("王五")
time.sleep(6)
driver.find_element_by_id("stu_table_toolbar_add_form_studentNo").send_keys("s000015")
time.sleep(6)
driver.find_element_by_id("stu_table_toolbar_add_form_idCard").send_keys("610524512545")
time.sleep(6)
driver.find_element_by_xpath("//*[@id='stu_table_toolbar_add_form']/div[4]/div/button/div/div/div").click()
time.sleep(5)
target=driver.find_element_by_xpath("//*[@id='stu_table_toolbar_add_modal']/div[2]/div/div[2]/ul/li[2]/a/span[2]")
ActionChains(driver).move_to_element("target").perform()
time.sleep(6)
driver.find_element_by_id("stu_table_toolbar_add_form_studentEmail").send_keys("123@qq.com")
time.sleep(3)
div1=driver.find_element_by_xpath("//*[@id='stu_table_toolbar_add_modal_dialog']/div/div[3]/div")
div1.find_element_by_xpath("//*[@id='stu_table_toolbar_add_form_submit']").click()
time.sleep(6)
driver.quit()